//! `OpenAPI` Documentation
//!
//! Central `OpenAPI` definition using utoipa. Serves Swagger UI at `/api/docs`.

#![expect(
    clippy::needless_for_each,
    reason = "triggered by utoipa OpenApi derive macro"
)]

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

/// `OpenAPI` documentation for the `VoiceChat` API.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "VoiceChat API",
        description = "Self-hosted voice and text chat platform API",
        version = "0.1.0",
        license(name = "MIT OR Apache-2.0"),
    ),
    tags(
        (name = "health", description = "Health check endpoints"),
        (name = "auth", description = "Authentication and user management"),
        (name = "channels", description = "Channel management"),
        (name = "messages", description = "Message operations"),
        (name = "dm", description = "Direct message conversations"),
        (name = "guilds", description = "Guild (server) management"),
        (name = "roles", description = "Role management"),
        (name = "invites", description = "Guild invite management"),
        (name = "categories", description = "Channel category management"),
        (name = "emojis", description = "Custom emoji management"),
        (name = "search", description = "Search endpoints"),
        (name = "admin", description = "System administration"),
        (name = "moderation", description = "Content moderation and reports"),
        (name = "social", description = "Friends and block list"),
        (name = "voice", description = "Voice channel and WebRTC"),
        (name = "crypto", description = "E2EE key management"),
        (name = "bots", description = "Bot and application management"),
        (name = "commands", description = "Slash command management"),
        (name = "webhooks", description = "Webhook management"),
        (name = "pins", description = "User pin management"),
        (name = "favorites", description = "Channel favorites"),
        (name = "reactions", description = "Message reactions"),
        (name = "unread", description = "Unread message tracking"),
        (name = "preferences", description = "User preferences"),
        (name = "pages", description = "Platform and guild pages"),
        (name = "connectivity", description = "Connection and session info"),
        (name = "discovery", description = "Public guild discovery and browsing"),
        (name = "settings", description = "Server settings and configuration"),
        (name = "setup", description = "Initial server setup"),
        (name = "uploads", description = "File upload operations"),
        (name = "overrides", description = "Channel permission overrides"),
        (name = "screenshare", description = "Screen sharing"),
    ),
    modifiers(&SecurityAddon),
    paths(
        // Health
        crate::api::health_check,
        // Auth - public
        crate::auth::handlers::register,
        crate::auth::handlers::login,
        crate::auth::handlers::refresh_token,
        crate::auth::handlers::forgot_password,
        crate::auth::handlers::reset_password,
        crate::auth::handlers::oidc_providers,
        crate::auth::handlers::oidc_authorize,
        crate::auth::handlers::oidc_callback,
        // Auth - protected
        crate::auth::handlers::logout,
        crate::auth::handlers::get_profile,
        crate::auth::handlers::update_profile,
        crate::auth::handlers::upload_avatar,
        crate::auth::handlers::mfa_setup,
        crate::auth::handlers::mfa_verify,
        crate::auth::handlers::mfa_disable,
        crate::auth::handlers::mfa_generate_backup_codes,
        crate::auth::handlers::mfa_backup_code_count,
        // Channels
        crate::chat::channels::create,
        crate::chat::channels::get,
        crate::chat::channels::update,
        crate::chat::channels::delete,
        crate::chat::channels::list_members,
        crate::chat::channels::add_member,
        crate::chat::channels::remove_member,
        crate::chat::channels::mark_as_read,
        // Messages
        crate::chat::messages::list,
        crate::chat::messages::create,
        crate::chat::messages::update,
        crate::chat::messages::delete,
        crate::chat::messages::list_thread_replies,
        crate::chat::messages::mark_thread_read,
        // Uploads
        crate::chat::uploads::upload_message_with_file,
        crate::chat::uploads::upload_file,
        crate::chat::uploads::get_attachment,
        crate::chat::uploads::download,
        // DM
        crate::chat::dm::list_dms,
        crate::chat::dm::create_dm,
        crate::chat::dm::get_dm,
        crate::chat::dm::leave_dm,
        crate::chat::dm::update_dm_name,
        crate::chat::dm::mark_as_read,
        crate::chat::dm::mark_all_dms_read,
        crate::chat::dm::upload_dm_icon,
        crate::chat::dm::get_dm_icon,
        // DM Search
        crate::chat::dm_search::search_dm_messages,
        // Overrides
        crate::chat::overrides::list_overrides,
        crate::chat::overrides::set_override,
        crate::chat::overrides::delete_override,
        // Guilds
        crate::guild::handlers::list_guilds,
        crate::guild::handlers::create_guild,
        crate::guild::handlers::get_guild,
        crate::guild::handlers::update_guild,
        crate::guild::handlers::delete_guild,
        crate::guild::handlers::leave_guild,
        crate::guild::handlers::list_members,
        crate::guild::handlers::kick_member,
        crate::guild::handlers::list_channels,
        crate::guild::handlers::reorder_channels,
        crate::guild::handlers::mark_all_channels_read,
        crate::guild::handlers::list_guild_bots,
        crate::guild::handlers::add_bot_to_guild,
        crate::guild::handlers::remove_bot_from_guild,
        crate::guild::handlers::list_guild_commands,
        crate::guild::handlers::get_guild_settings,
        crate::guild::handlers::update_guild_settings,
        // Roles
        crate::guild::roles::list_roles,
        crate::guild::roles::create_role,
        crate::guild::roles::update_role,
        crate::guild::roles::delete_role,
        crate::guild::roles::assign_role,
        crate::guild::roles::remove_role,
        // Invites
        crate::guild::invites::list_invites,
        crate::guild::invites::create_invite,
        crate::guild::invites::delete_invite,
        crate::guild::invites::join_via_invite,
        // Categories
        crate::guild::categories::list_categories,
        crate::guild::categories::create_category,
        crate::guild::categories::update_category,
        crate::guild::categories::delete_category,
        crate::guild::categories::reorder_categories,
        // Emojis
        crate::guild::emojis::list_emojis,
        crate::guild::emojis::get_emoji,
        crate::guild::emojis::create_emoji,
        crate::guild::emojis::update_emoji,
        crate::guild::emojis::delete_emoji,
        // Guild Search
        crate::guild::search::search_messages,
        // Discovery
        crate::discovery::handlers::browse_guilds,
        crate::discovery::handlers::join_discoverable,
        // Guild Pages
        crate::pages::handlers::list_guild_pages,
        crate::pages::handlers::create_guild_page,
        crate::pages::handlers::update_guild_page,
        crate::pages::handlers::delete_guild_page,
        crate::pages::handlers::reorder_guild_pages,
        crate::pages::handlers::get_guild_page,
        crate::pages::handlers::accept_guild_page,
        // Admin
        crate::admin::handlers::get_admin_status,
        crate::admin::handlers::get_admin_stats,
        crate::admin::handlers::elevate_session,
        crate::admin::handlers::de_elevate_session,
        crate::admin::handlers::list_users,
        crate::admin::handlers::export_users_csv,
        crate::admin::handlers::get_user_details,
        crate::admin::handlers::list_guilds,
        crate::admin::handlers::export_guilds_csv,
        crate::admin::handlers::get_guild_details,
        crate::admin::handlers::get_audit_log,
        crate::moderation::admin_handlers::list_reports,
        crate::moderation::admin_handlers::report_stats,
        crate::moderation::admin_handlers::get_report,
        crate::moderation::admin_handlers::claim_report,
        crate::moderation::admin_handlers::resolve_report,
        crate::admin::handlers::ban_user,
        crate::admin::handlers::unban_user,
        crate::admin::handlers::bulk_ban_users,
        crate::admin::handlers::delete_user,
        crate::admin::handlers::suspend_guild,
        crate::admin::handlers::unsuspend_guild,
        crate::admin::handlers::bulk_suspend_guilds,
        crate::admin::handlers::delete_guild,
        crate::admin::handlers::create_announcement,
        crate::admin::handlers::get_auth_settings,
        crate::admin::handlers::update_auth_settings,
        crate::admin::handlers::list_oidc_providers,
        crate::admin::handlers::create_oidc_provider,
        crate::admin::handlers::update_oidc_provider,
        crate::admin::handlers::delete_oidc_provider,
        // Moderation
        crate::moderation::handlers::create_report,
        crate::moderation::filter_handlers::list_filter_configs,
        crate::moderation::filter_handlers::update_filter_configs,
        crate::moderation::filter_handlers::list_custom_patterns,
        crate::moderation::filter_handlers::create_custom_pattern,
        crate::moderation::filter_handlers::update_custom_pattern,
        crate::moderation::filter_handlers::delete_custom_pattern,
        crate::moderation::filter_handlers::list_moderation_log,
        crate::moderation::filter_handlers::test_filter,
        // Social
        crate::social::friends::send_friend_request,
        crate::social::friends::list_friends,
        crate::social::friends::list_pending_requests,
        crate::social::friends::list_blocked,
        crate::social::friends::accept_friend_request,
        crate::social::friends::reject_friend_request,
        crate::social::friends::block_user,
        crate::social::friends::unblock_user,
        crate::social::friends::remove_friend,
        // Voice
        crate::voice::handlers::get_ice_servers,
        crate::voice::call_handlers::get_call,
        crate::voice::call_handlers::start_call,
        crate::voice::call_handlers::join_call,
        crate::voice::call_handlers::decline_call,
        crate::voice::call_handlers::leave_call,
        // Screen share
        crate::chat::screenshare::check,
        crate::chat::screenshare::start,
        crate::chat::screenshare::stop,
        // Crypto
        crate::crypto::handlers::upload_keys,
        crate::crypto::handlers::get_backup,
        crate::crypto::handlers::upload_backup,
        crate::crypto::handlers::get_backup_status,
        crate::crypto::handlers::get_own_devices,
        crate::crypto::handlers::get_user_keys,
        crate::crypto::handlers::claim_prekey,
        // Bots
        crate::api::bots::list_applications,
        crate::api::bots::create_application,
        crate::api::bots::get_application,
        crate::api::bots::delete_application,
        crate::api::bots::create_bot,
        crate::api::bots::reset_bot_token,
        crate::api::bots::update_gateway_intents,
        // Commands
        crate::api::commands::list_commands,
        crate::api::commands::register_commands,
        crate::api::commands::delete_all_commands,
        crate::api::commands::delete_command,
        // Webhooks
        crate::webhooks::handlers::list_webhooks,
        crate::webhooks::handlers::create_webhook,
        crate::webhooks::handlers::get_webhook,
        crate::webhooks::handlers::update_webhook,
        crate::webhooks::handlers::delete_webhook,
        crate::webhooks::handlers::test_webhook,
        crate::webhooks::handlers::list_deliveries,
        // Reactions
        crate::api::reactions::get_reactions,
        crate::api::reactions::add_reaction,
        crate::api::reactions::remove_reaction,
        // Pins
        crate::api::pins::list_pins,
        crate::api::pins::create_pin,
        crate::api::pins::reorder_pins,
        crate::api::pins::update_pin,
        crate::api::pins::delete_pin,
        // Favorites
        crate::api::favorites::list_favorites,
        crate::api::favorites::reorder_channels,
        crate::api::favorites::reorder_guilds,
        crate::api::favorites::add_favorite,
        crate::api::favorites::remove_favorite,
        // Unread
        crate::api::unread::get_unread_aggregate,
        crate::api::unread::mark_all_read,
        // Preferences
        crate::api::preferences::get_preferences,
        crate::api::preferences::update_preferences,
        // Connectivity
        crate::connectivity::handlers::get_summary,
        crate::connectivity::handlers::get_sessions,
        crate::connectivity::handlers::get_session_detail,
        // Pages
        crate::pages::handlers::list_platform_pages,
        crate::pages::handlers::get_platform_page,
        crate::pages::handlers::create_platform_page,
        crate::pages::handlers::get_pending_acceptance,
        crate::pages::handlers::reorder_platform_pages,
        crate::pages::handlers::update_platform_page,
        crate::pages::handlers::delete_platform_page,
        crate::pages::handlers::accept_page,
        // Settings
        crate::api::settings::get_server_settings,
        crate::api::settings::get_upload_limits,
        // Setup
        crate::api::setup::status,
        crate::api::setup::get_config,
        crate::api::setup::complete,
        // Global Search
        crate::api::global_search::search_all,
    ),
    components(schemas(
        // Health
        crate::api::HealthResponse,
        // Auth
        crate::auth::handlers::RegisterRequest,
        crate::auth::handlers::LoginRequest,
        crate::auth::handlers::RefreshRequest,
        crate::auth::handlers::LogoutRequest,
        crate::auth::handlers::AuthResponse,
        crate::auth::handlers::UserProfile,
        crate::auth::handlers::MfaSetupResponse,
        crate::auth::handlers::MfaBackupCodesResponse,
        crate::auth::handlers::MfaBackupCodeCountResponse,
        crate::auth::handlers::MfaVerifyRequest,
        crate::auth::handlers::UpdateProfileRequest,
        crate::auth::handlers::UpdateProfileResponse,
        crate::auth::handlers::ForgotPasswordRequest,
        crate::auth::handlers::ResetPasswordRequest,
        crate::auth::error::ErrorResponse,
        // DB Models
        crate::db::AuthMethod,
        crate::db::UserStatus,
        crate::db::ChannelType,
        crate::db::Channel,
        // Note: db::User intentionally excluded — contains password_hash, mfa_secret
        crate::db::Message,
        crate::db::Role,
        crate::db::FileAttachment,
        crate::db::PublicOidcProvider,
        crate::db::AuthMethodsConfig,
        crate::db::ChannelUnread,
        crate::db::GuildUnreadSummary,
        crate::db::UnreadAggregate,
        crate::db::BotApplication,
        crate::db::SlashCommand,
        crate::db::GuildBotInstallation,
        // Chat - Channels
        crate::chat::channels::ChannelResponse,
        crate::chat::channels::CreateChannelRequest,
        crate::chat::channels::UpdateChannelRequest,
        crate::chat::channels::AddMemberRequest,
        crate::chat::channels::MemberResponse,
        crate::chat::channels::MarkChannelAsReadRequest,
        // Chat - Messages
        crate::chat::messages::AuthorProfile,
        crate::chat::messages::AttachmentInfo,
        crate::chat::messages::MentionType,
        crate::chat::messages::ThreadInfoResponse,
        crate::chat::messages::MessageResponse,
        crate::chat::messages::ReactionInfo,
        crate::chat::messages::ListMessagesQuery,
        crate::chat::messages::CreateMessageRequest,
        crate::chat::messages::ListThreadRepliesQuery,
        crate::chat::messages::UpdateMessageRequest,
        crate::chat::messages::CursorPaginatedResponse<crate::chat::messages::MessageResponse>,
        // Chat - DM
        crate::chat::dm::CreateDMRequest,
        crate::chat::dm::DMResponse,
        crate::chat::dm::LastMessagePreview,
        crate::chat::dm::DMListResponse,
        crate::chat::dm::DMParticipant,
        crate::chat::dm::UpdateDMNameRequest,
        crate::chat::dm::DMIconResponse,
        crate::chat::dm::MarkAsReadRequest,
        crate::chat::dm::MarkAsReadResponse,
        // Chat - DM Search
        crate::chat::dm_search::DmSearchQuery,
        crate::chat::dm_search::DmSearchAuthor,
        crate::chat::dm_search::DmSearchResult,
        crate::chat::dm_search::DmSearchResponse,
        // Chat - Overrides
        crate::chat::overrides::OverrideResponse,
        crate::chat::overrides::SetOverrideRequest,
        // Guild
        crate::guild::types::Guild,
        crate::guild::types::GuildWithMemberCount,
        crate::guild::types::CreateGuildRequest,
        crate::guild::types::UpdateGuildRequest,
        crate::guild::types::JoinGuildRequest,
        crate::guild::types::GuildMember,
        crate::guild::types::GuildInvite,
        crate::guild::types::CreateInviteRequest,
        crate::guild::types::InviteResponse,
        crate::guild::types::CreateRoleRequest,
        crate::guild::types::UpdateRoleRequest,
        crate::guild::types::RoleResponse,
        crate::guild::types::GuildEmoji,
        crate::guild::types::CreateEmojiRequest,
        crate::guild::types::UpdateEmojiRequest,
        crate::guild::types::GuildSettings,
        crate::guild::types::UpdateGuildSettingsRequest,
        crate::guild::types::GuildCommandInfo,
        crate::guild::handlers::ChannelWithUnread,
        crate::guild::handlers::InstalledBot,
        crate::guild::handlers::ChannelPosition,
        crate::guild::handlers::ReorderChannelsRequest,
        // Guild - Categories
        crate::guild::categories::Category,
        crate::guild::categories::CreateCategoryRequest,
        crate::guild::categories::UpdateCategoryRequest,
        crate::guild::categories::ReorderRequest,
        crate::guild::categories::CategoryPosition,
        // Discovery
        crate::discovery::types::DiscoverSort,
        crate::discovery::types::DiscoverableGuild,
        crate::discovery::types::DiscoverResponse,
        crate::discovery::types::JoinDiscoverableResponse,
        // Guild - Search
        crate::guild::search::SearchQuery,
        crate::guild::search::SearchAuthor,
        crate::guild::search::SearchResult,
        crate::guild::search::SearchResponse,
        // Admin
        crate::admin::types::ElevateRequest,
        crate::admin::types::ElevateResponse,
        crate::admin::types::GlobalBanRequest,
        crate::admin::types::SuspendGuildRequest,
        crate::admin::types::CreateAnnouncementRequest,
        crate::admin::types::AdminStatusResponse,
        crate::admin::types::AdminStatsResponse,
        crate::admin::types::BulkBanRequest,
        crate::admin::types::BulkBanResponse,
        crate::admin::types::BulkSuspendRequest,
        crate::admin::types::BulkSuspendResponse,
        crate::admin::types::BulkActionFailure,
        crate::admin::handlers::PaginationParams,
        crate::admin::handlers::AuditLogParams,
        crate::admin::handlers::UserSummary,
        crate::admin::handlers::GuildSummary,
        crate::admin::handlers::AuditLogEntryResponse,
        crate::admin::handlers::DeElevateResponse,
        crate::admin::handlers::UserGuildMembership,
        crate::admin::handlers::UserDetailsResponse,
        crate::admin::handlers::GuildMemberInfo,
        crate::admin::handlers::GuildOwnerInfo,
        crate::admin::handlers::GuildDetailsResponse,
        crate::admin::handlers::PaginatedResponse<crate::admin::handlers::UserSummary>,
        crate::admin::handlers::PaginatedResponse<crate::admin::handlers::GuildSummary>,
        crate::admin::handlers::PaginatedResponse<crate::admin::handlers::AuditLogEntryResponse>,
        crate::admin::handlers::DeleteResponse,
        crate::admin::handlers::AnnouncementResponse,
        crate::admin::handlers::AuthSettingsResponse,
        crate::admin::handlers::OidcProviderResponse,
        // Social
        crate::social::types::FriendshipStatus,
        crate::social::types::Friendship,
        crate::social::types::Friend,
        crate::social::types::SendFriendRequestBody,
        // Moderation
        crate::moderation::types::ReportCategory,
        crate::moderation::types::ReportStatus,
        crate::moderation::types::ReportTargetType,
        crate::moderation::types::CreateReportRequest,
        crate::moderation::types::ResolveReportRequest,
        crate::moderation::types::ListReportsQuery,
        crate::moderation::types::Report,
        crate::moderation::types::ReportResponse,
        crate::moderation::types::ReportStatsResponse,
        crate::moderation::types::PaginatedReports,
        // Moderation - Filters
        crate::moderation::filter_types::FilterCategory,
        crate::moderation::filter_types::FilterAction,
        crate::moderation::filter_types::GuildFilterConfig,
        crate::moderation::filter_types::GuildFilterPattern,
        crate::moderation::filter_types::CreatePatternRequest,
        crate::moderation::filter_types::UpdatePatternRequest,
        crate::moderation::filter_types::UpdateFilterConfigsRequest,
        crate::moderation::filter_types::TestFilterRequest,
        crate::moderation::filter_types::TestFilterResponse,
        crate::moderation::filter_types::FilterMatchResponse,
        crate::moderation::filter_types::PaginatedModerationLog,
        // Voice - Calls
        crate::voice::call_handlers::CallStateResponse,
        crate::voice::call_handlers::CallApiError,
        crate::voice::call::CallState,
        // Bots
        crate::api::bots::CreateApplicationRequest,
        crate::api::bots::ApplicationResponse,
        crate::api::bots::BotTokenResponse,
    ))
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
    }
}
